version: "3"

services:
  
  hello:
    build:
      context: ./server
      dockerfile: Dockerfile

  proxy:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:8080"

#  <srv_name>:
#    image: <image_name>
#    container_name: <container_name>
#    hostname: <hostname>
#    restart: unless-stopped
#    environment:
#      TZ: "Europe/Moscow"
#    networks:
#      - default

#networks:
#  default:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16